model:
  dimension: 12160
  ndays: 5.0
data:
  data_folder: /home/data/data_data_assimilation/shallow_water/test
  nsamples: 10
  nvectors: 5
architecture:
  class: SW_TransUNet
  rank: 2000
  n_layers: 0
  neurons_per_layer: 0
  batch_size: 2
  lr: 1e-4
  n_rnd_vectors: 0
optimizer:
  epochs: 50
DA:
  n_cycle: 10
  n_outer: 3
  n_inner: 50
  observation:
    observation_operator: "eta" # or "eta"
    observation_sigma2: "id"
  background:
    bck_sigma2: [5.0, 0.1, 0.1]
    bck_state: /home/shallow/data/mean_state.nc
misc:
  mlflow: true
