model:
  dimension: 12160
data:
  data_folder: /data/data_data_assimilation/shallow_water/basic_id
  nsamples: 1000
architecture:
  class: SW_TransUNet
  rank: 2000
  n_layers: 0
  neurons_per_layer: 0
  batch_size: 10
  lr: 1e-6
  n_rnd_vectors: 0
optimizer:
  epochs: 500
DA:
  n_cycle: 10
  n_outer: 5
  n_inner: 100
  model_error_sqrt: 0.5
  obs_error_sqrt: 3.0
  # log_file: /home/smoke/artifacts/DA_logs.csv
  # log_file: /GNlearning/smoke/artifacts/DA_logs.csv
misc:
  mlflow: true
