model:
  dimension: 20
  window: 10
data:
  data_path: /root/raw_data/data_20.pkl
  nsamples: 20000
architecture:
  rank: 15
  n_layers: 5
  neurons_per_layer: 0
  batch_size: 64
  lr: 1e-4
optimizer:
  epochs: 250
DA:
  n_cycle: 10
  n_outer: 5
  n_inner: 100
  log_file: /home/smoke/DA_logs.csv
