model:
  dimension: 40
  window: 10
data:
  data_path: /root/raw_data/data_40.pkl
  nsamples: 10000
architecture:
  class: SVDConvolutional
  rank: 30
  n_layers: 6
  neurons_per_layer: 0
  batch_size: 32
  lr: 1e-4
  n_rnd_vectors: 5
optimizer:
  epochs: 200
DA:
  n_cycle: 5
  n_outer: 5
  n_inner: 100
  model_error_sqrt: 0.5
  obs_error_sqrt: 3.0
  log_file: /home/smoke/artifacts/DA_logs.csv
