model:
  dimension: 40
  window: 10
data:
  # data_path: /root/raw_data/data_100.pkl
  # data_folder: /root/raw_data/data_40_large_window_20
  data_folder: /root/raw_data/data_40_large
  nsamples: 50000
architecture:
  class: SVDConvolutionalSPAI
  rank: 40
  n_layers: 8
  neurons_per_layer: 0
  batch_size: 8
  lr: 1e-5
  n_rnd_vectors: 0
optimizer:
  epochs: 25
DA:
  n_cycle: 20
  n_outer: 5
  n_inner: 100
  model_error_sqrt: 0.5
  obs_error_sqrt: 3.0
  log_file: /home/smoke/artifacts/DA_logs.csv
