model:
  dimension: 100
  window: 10
data:
  data_path: /root/raw_data/data_100.pkl
  nsamples: 5000
architecture:
  class: SVDConvolutional
  rank: 50
  n_layers: 6
  neurons_per_layer: 0
  batch_size: 8
  lr: 1e-4
  n_rnd_vectors: 100
optimizer:
  epochs: 100
DA:
  n_cycle: 5
  n_outer: 5
  n_inner: 100
  model_error_sqrt: 0.5
  obs_error_sqrt: 3.0
  log_file: /home/smoke/artifacts/DA_logs.csv
