vars:
  - abs_path: /home
  - smoke_path: /home/smoke

stages:
  generate_data:
    cmd: python3.10 ${abs_path}/prec_data/data_generation.py --config ${smoke_path}/data_params.yaml
    deps:
      - ${abs_path}/prec_data/data_generation.py
      - ${smoke_path}/data_params.yaml
    params:
      - data_params.yaml:
          - model.dimension
          - model.nsamples
          - model.window
          - model.output
    outs:
      - /root/raw_data/data.pkl

  train:
    cmd: source ${abs_path}/.set_environment_variables.sh && python3.10 ${smoke_path}/training.py --config config_smoke.yaml --exp-name smoke_train_tr
    deps:
      - training.py
      - config_smoke.yaml
      - ../prec_data/data.py
      - /root/raw_data/data.pkl
    params:
      - config_smoke.yaml:
          - data.dimension
          - architecture.rank
          - architecture.n_layers
          - architecture.neurons_per_layer
          - architecture.batch_size
          - optimizer.epochs
    metrics:
      - metrics.yaml
    outs:
      - mlflow_run_id.yaml
      - logs.csv

  inference:
    deps:
      - mlflow_run_id.yaml
      - training.py
      - config_smoke.yaml
    cmd: source ../.set_environment_variables.sh && python3.10 inference.py --run-id-yaml mlflow_run_id.yaml
    plots:
      - /home/figures/condition_numbers.png
      - /home/figures/inference_approx.png
      - /home/figures/inference_precondition.png

params:
  - data_params.yaml
  - config_smoke.yaml

plots:
  - logs.csv:
      template: linear
      x: step
      y: Loss/train_loss
