params:
  - config.yaml
vars:
  - abs_path: /home
  - smoke_path: /home/smoke
  - data_path: /root/raw_data
  - artifacts_path: /home/smoke/artifacts

stages:
  generate_data:
    cmd: >-
      python3.10 ${abs_path}/prec_data/data_generation.py
      --config ${smoke_path}/config.yaml
    deps:
      - ${abs_path}/prec_data/data_generation.py
    params:
      - config.yaml:
          - model.dimension
          - model.window
          - data.nsamples
          - data.data_path
    vars:
      - config.yaml:data
    outs:
      - ${data.data_path}

  train:
    vars:
      - config.yaml:data
    cmd: >-
      source ${abs_path}/.set_environment_variables.sh &&
      python3.10 ${smoke_path}/training.py
      --config config.yaml
      --exp-name smoke_train_tr
    deps:
      - config.yaml
      - training.py
      - ${abs_path}/prec_data/data.py
      - ${data.data_path}
    params:
      - config.yaml:
          - data.data_path
          - model.dimension
          - architecture.class
          - architecture.rank
          - architecture.n_layers
          - architecture.batch_size
          - optimizer.epochs
    metrics:
      - ${artifacts_path}/metrics.yaml
    outs:
      - ${artifacts_path}/mlflow_run_id.yaml
      - ${artifacts_path}/training_logs.csv

  test:
    deps:
      - config.yaml
      - ${artifacts_path}/mlflow_run_id.yaml
      - training.py
      - test.py
    cmd: >-
      source ${abs_path}/.set_environment_variables.sh && 
      python3.10 test.py
      --run-id-yaml ${artifacts_path}/mlflow_run_id.yaml
    params:
      - config.yaml:
          - data.data_path
    plots:
      - ${artifacts_path}/condition_numbers.png
      - ${artifacts_path}/inference_approx.png
      - ${artifacts_path}/inference_precondition.png
      - ${artifacts_path}/sanity_check.png

  data_assim:
    deps:
      - config.yaml
      - ${artifacts_path}/training_logs.csv
      - ${artifacts_path}/mlflow_run_id.yaml
    cmd: >-
      source ${abs_path}/.set_environment_variables.sh &&
      python3.10 data_assimilation_benchmark.py
      --config config.yaml
      --run-id-yaml ${artifacts_path}/mlflow_run_id.yaml
    params:
      - config.yaml:
          - model.window
          - DA.n_cycle
          - DA.n_outer
          - DA.n_inner
    outs:
      - ${artifacts_path}/DA_logs.csv
      - ${artifacts_path}/res_inner_loop.png
    # plots:

plots:
  - ${artifacts_path}/training_logs.csv:
      template: linear
      x: step
      y: Loss/train_loss
  - ${artifacts_path}/res_inner_loop.png
  - ${artifacts_path}/condition_numbers.png
  - ${artifacts_path}/inference_approx.png
  - ${artifacts_path}/inference_precondition.png
  # - DA_logs.csv:
  #     template: scatter_log.json
  #     x: nouter
  #     y: condprec
