params:
  - config.yaml
vars:
  - abs_path: /home
  - smoke_path: /home/smoke
  - data_path: /root/raw_data
  - fig_path: /home/figures

stages:
  generate_data:
    cmd: >-
      python3.10 ${abs_path}/prec_data/data_generation.py
      --config ${smoke_path}/config.yaml
    deps:
      - ${abs_path}/prec_data/data_generation.py
      # - ${smoke_path}/data_params.yaml
    params:
      - config.yaml:
          - model.dimension
          - model.window
          - data.nsamples
          - data.data_path
    vars:
      - config.yaml:data
    outs:
      - ${data.data_path}

  train:
    vars:
      - config.yaml:data
    cmd: >-
      source ${abs_path}/.set_environment_variables.sh &&
      python3.10 ${smoke_path}/training.py
      --config config.yaml
      --exp-name smoke_train_tr
    deps:
      - config.yaml
      - training.py
      - ${abs_path}/prec_data/data.py
      - ${data.data_path}
      # - ${data_path}/data.pkl
    params:
      - config.yaml:
          - data.data_path
          - model.dimension
          - architecture.rank
          - architecture.n_layers
          - architecture.batch_size
          - optimizer.epochs
    metrics:
      - metrics.yaml
    outs:
      - mlflow_run_id.yaml
      - logs.csv

  test:
    deps:
      - mlflow_run_id.yaml
      - training.py
      - config.yaml
      - test.py
    cmd: >-
      source ${abs_path}/.set_environment_variables.sh && 
      python3.10 test.py
      --run-id-yaml mlflow_run_id.yaml
    params:
      - config.yaml:
          - data.data_path
    plots:
      - ${fig_path}/condition_numbers.png
      - ${fig_path}/inference_approx.png
      - ${fig_path}/inference_precondition.png
      - ${fig_path}/sanity_check.png

  data_assim:
    deps:
      # - config_smoke.yaml
      - logs.csv
      - mlflow_run_id.yaml
      # - config_DA.yaml
    cmd: >-
      source ${abs_path}/.set_environment_variables.sh &&
      python3.10 data_assimilation_benchmark.py
      --config config.yaml
      --run-id-yaml mlflow_run_id.yaml
    params:
      - config.yaml:
          - model.window
          - DA.n_cycle
          - DA.n_outer
          - DA.n_inner
    outs:
      - ${smoke_path}/DA_logs.csv
    plots:
      - ${fig_path}/res_inner_loop.png

plots:
  - logs.csv:
      template: linear
      x: step
      y: Loss/train_loss
  - DA_logs.csv:
      template: scatter_log.json
      x: CGiter
      y: condprec
  # - ${fig_path}/res_inner_loop.png
  # - ${fig_path}/condition_numbers.png
  # - ${fig_path}/inference_approx.png
  # - ${fig_path}/inference_precondition.png
