stages:
  generate_data:
    cmd: python3.10 ../prec_data/data_generation.py --config data_params.yaml
    deps:
    - ../prec_data/data_generation.py
    - ../prec_data/data.py
    - data_params.yaml
    params:
      - data_params.yaml:
        - model.dimension
        - model.nsamples
        - model.window
        - model.output
    outs:
    - /root/raw_data/data.pkl

  smoke_train:
    cmd: source ../.set_environment_variables.sh && python3.10 training.py --config config_smoke.yaml --exp-name smoke_train_tr
    deps:
    - training.py
    - config_smoke.yaml
    - /root/raw_data/data.pkl
    metrics:
    - metrics.yaml

params:
  - data_params.yaml
  - config_smoke.yaml
