stages:
  generate_data:
    cmd: python3.8 ../prec_data/data_generation.py --config data_params.yaml
    deps:
    - ../prec_data/data_generation.py
    - ../prec_data/data.py
    - data_params.yaml
    params:
      - smoke/data_params.yaml:
        - model.dimension
        - model.nsamples
        - model.window
        - model.output
    outs:
    - raw_data/data.pkl

  smoke_train:
    cmd: python3.8 training_smoke.py --config config_smoke.yaml --exp-name smoke_train
    deps:
    - training_smoke.py
    - config_smoke.yaml
    - ../raw_data/data.pkl

params:
  - data_params.yaml
  - config_smoke.yaml
