stages:
  generate_data:
    cmd: python3.10 ../prec_data/data_generation.py --config data_params.yaml
    deps:
      - ../prec_data/data_generation.py
      - data_params.yaml
    params:
      - data_params.yaml:
          - model.dimension
          - model.nsamples
          - model.window
          - model.output
    outs:
      - /root/raw_data/data.pkl

  train:
    cmd: source ../.set_environment_variables.sh && python3.10 training.py --config config_smoke.yaml --exp-name smoke_train_tr
    deps:
      - training.py
      - config_smoke.yaml
      - ../prec_data/data.py
      - /root/raw_data/data.pkl
    metrics:
      - metrics.yaml
    # outs:
    #   - metrics.yaml
    # plots:
    #   - /root/log_dump/smoke/lightning_logs/smoke/metrics.csv
    #     # x: epoch
    #     # y: [Loss/train_loss, Loss/val_loss]

  inference:
    vars:
      - metrics.yaml:run_id
    cmd: source ../.set_environment_variables.sh && python3.10 inference.py --run-id ${run_id}
    # outs:
    #   - /home/figures/condition_numbers_${run_id}.png
    #   - /home/figures/inference_approx_${run_id}.png
    #   - /home/figures/inference_precondition_${run_id}.png
    plots:
      - /home/figures/condition_numbers_${run_id}.png
      - /home/figures/inference_approx_${run_id}.png
      - /home/figures/inference_precondition_${run_id}.png

params:
  - data_params.yaml
  - config_smoke.yaml
